version: "3.8"
services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
  web:
    build: ./web
    ports:
      - "5173:5173"
    command: npm run dev
    env_file:
      - .env